---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 85448.
--- DateTime: 2025/12/30 10:22
---
-- 基于阻塞队列实现异步下单
---- 1.参数列表
---- 1.1 秒杀券id
--local seckillId = ARGV[1];
---- 1.2 用户id
--local userId = ARGV[2];
--
---- 2.数据Key
---- 2.1 秒杀券库存Key
--local stockKey = 'seckill:stock:' .. seckillId;
---- 2.2 订单Key
--local orderKey = 'seckill:order:' .. seckillId;
--
---- 3.判断库存是否充足以及是否一人一单
---- 3.1 判断库存是否充足
--if(tonumber(redis.call('get', stockKey)) <= 0) then
--    return 1;
--end
--
---- 3.2 判断是否一人一单
--if(redis.call('sismember', orderKey, userId) == 1) then
--    return 2;
--end
--
---- 如果都满足则修改Redis中的数据，并返回0
--redis.call('incrby', stockKey, -1);
--redis.call('sadd', orderKey, userId);
--return 0

-- 基于消息队列实现异步下单
-- 1.参数列表
-- 1.1 秒杀券id
local voucherId = ARGV[1];
-- 1.2 用户id
local userId = ARGV[2];
-- 1.3 订单id
--local orderId = ARGV[3];

-- 2.数据Key
-- 2.1 秒杀券库存Key
local stockKey = 'seckill:stock:' .. voucherId;
-- 2.2 订单Key
local orderKey = 'seckill:order:' .. voucherId;

-- 3.判断库存是否充足以及是否一人一单
-- 3.1 判断库存是否充足
if(tonumber(redis.call('get', stockKey)) <= 0) then
    return 1;   -- 返回1来表示库存不足
end

-- 3.2 判断是否一人一单
if(redis.call('sismember', orderKey, userId) == 1) then
    return 2;   -- 返回2来表示用户已下单
end

-- 如果都满足则修改Redis中的数据，并将消息发送到消息队列中，然后返回0
redis.call('incrby', stockKey, -1);
redis.call('sadd', orderKey, userId);
--redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0