---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 85448.
--- DateTime: 2025/12/28 22:05
---

if(redis.call('get', KEYS[1]) == ARGV[1]) then
    return redis.call('del', KEYS[1])
end
return 0

